#!/bin/bash

set -o errexit

if ! [[ ${TESTDIR+x} ]]; then
  echo "ERROR: WRONG CONTEXT"
  exit 1
fi

BUILDDIR="../tagvfs"
pushd "${BUILDDIR}"
# make clean
make
popd

cp "${BUILDDIR}/tagvfs.ko" "${TESTDIR}"/

sudo insmod ./${TESTDIR}/tagvfs.ko

# Get debug information in case of memleak detection
if [[ ${TEST_MEMLEAK+x} ]]; then
  BASEPATH=$(pwd)
  pushd /sys/module/tagvfs/sections
  echo ".text .data .bss" > ${BASEPATH}/sections.txt
  sudo cat .text .data .bss >> ${BASEPATH}/sections.txt
  popd

  objdump -DS ./${TESTDIR}/tagvfs.ko > disasm.txt
fi

exit 0
