#!/bin/bash


if ! [[ ${TESTDIR+x} ]]; then
  echo "ERROR: WRONG CONTEXT"
  exit 1
fi

# ---- TRAPS ---
SCRIPT_PATH=$(pwd)
TESTDIR_PATH=""

trap 'ExitHandler' EXIT
ExitHandler() {
  ${SHELL} ${SCRIPT_PATH}/comm_wait_umount ${TESTDIR_PATH}/only-tags-feature
}


function CheckTag1Exist() {
  EXIST_TAG1="0"
  for f in ${TAGS_DIR}/* ; do
    if [[ "$(basename $f)" == "tag1" ]]; then
      EXIST_TAG1="1"
    fi
  done

  if ! [[ "${EXIST_TAG1}" == "1" ]]; then
    echo "ERROR: BASE FUNCTIONS: Tag tag1 is created but it hasn't listed in directory"
    exit 1
  fi

  EXIST_TAG1="0"
  for f in ${ONLY_TAGS_DIR}/* ; do
    if [[ $(basename $f) == "tag1" ]]; then
      EXIST_TAG1="1"
    fi
  done

  if ! [[ "${EXIST_TAG1}" == "1" ]]; then
    echo "ERROR: BASE FUNCTIONS: Tag tag1 is created but it hasn't listed in only-tags directory"
    exit 1
  fi
}


# ------------------
# ------------------

echo -----
echo "TEST: only-tags feature test"

set -o errexit

pushd ${TESTDIR} > /dev/null
TESTDIR_PATH=$(pwd)

# Root path of mount point
ROOT_PATH="${TESTDIR_PATH}/only-tags-feature"
mkdir ${ROOT_PATH}
sudo mount -t tagvfs ${TESTDIR_PATH}/only-tags-feature.tag ${ROOT_PATH}/

TAGS_DIR=${ROOT_PATH}/tags
ONLY_TAGS_DIR=${ROOT_PATH}/only-tags

# Check tag creation
# -----
mkdir "${ONLY_TAGS_DIR}/tag1"

set +o errexit
if [[ $(mkdir ${ONLY_TAGS_DIR}/tag1 > /dev/null 2> /dev/null) ]]; then
  echo "ERROR: BASE FUNCTIONS: double creation of the same tag"
  exit 1
fi
set -o errexit

${SHELL} ${SCRIPT_PATH}/comm_check_exist "${ONLY_TAGS_DIR}/tag1"

rm -frd "${ONLY_TAGS_DIR}/tag1"

set +o errexit
${SHELL} ${SCRIPT_PATH}/comm_check_exist "${ONLY_TAGS_DIR}/tag1"
if [[ $? -eq 0 ]]; then
  echo "ERROR: ONLY-TAGS FEATURE: removing tag don't remove it"
  exit 1
fi
set -o errexit


${SHELL} ${SCRIPT_PATH}/comm_wait_umount ${TESTDIR}/only-tags-feature

popd > /dev/null

echo --- OK: only-tags feature ---
